// <auto-generated />
namespace PFMO.Web.Migrations.PFMO_Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Models_Changed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Models_Changed));
        
        string IMigrationMetadata.Id
        {
            get { return "201603091214304_Models_Changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
